
[context.master]
  [context.master.environment]
    REACT_APP_BRANCH = "master"

[context.develop]
  [context.develop.environment]
    REACT_APP_BRANCH = "develop"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200